services:
  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - .env
    networks:
      - default
  bot:
    build: ./contact_bot
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./contact_bot/logs:/opt/app/logs
    depends_on:
      - api
    networks:
      - default
  api:
    build: ./api
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - ${API_PORT}
    volumes:
      - ./api/logs:/opt/app/logs
    depends_on:
      - admin
      - postgres
    networks:
      - default
  admin:
    build:
      context: admin
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./admin/static:/var/www/:rw
    expose:
      - "80"
    networks:
      - default
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./admin/static:/var/www/:ro
      - ./letsencrypt-certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - admin
      - api
      - certbot
    networks:
      - default
  db_cleaner:
    build: ./cleaner
    env_file:
      - .env
    restart: always
    volumes:
      - ./cleaner/logs:/opt/app/logs
    depends_on:
      - admin
      - postgres
    networks:
      - default
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt-certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'"
    networks:
      - default
volumes:
  postgres_data:


networks:
  default:
    driver: bridge
